language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

    include:
        - php: 5.3
          env: COMPOSER_FLAGS="--prefer-lowest"
          dist: precise
        - php: 7.0
          before_script:
            - curl -sSfL -o ~/.phpenv/versions/7.0/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
        - php: hhvm
          before_script:
            - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar


before_install:
    - travis_retry composer self-update

install:
    - composer update ${COMPOSER_FLAGS} --no-interaction
